version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.12

  api:
    build: api/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
    volumes:
      - db-data:/db
    networks:
      app_net:
        ipv4_address: 172.16.238.11

volumes:
  db-data:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"